@Restaurants.API_HostAddress = https://localhost:7028

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET https://localhost:7028/api/Restaurants/2002

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
      "Name": "Mohammed",
    "Description": "An",
    "Category": "any thing",

        "City": "Cairo",
        "Street": "any thing",
        "PostalCode": "anything",
    "ContactEmail": "example@example.com",
    "ContactNumber": "0101010"
}
###
