@Restaurants.API_HostAddress = https://localhost:7028

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/6

###

@restaurantId=6
GET {{Restaurants.API_HostAddress}}/api/restaurant/6/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/6/dishes
Content-Type: application/json


{
  "name": "asdasd",
  "description": "dasd",
  "price": 11,
  "kiloCalories": 11
}


###
